name: customer_flutter_offline
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.12.2


dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^1.0.8
  get_it: ^9.2.1
  injectable: ^3.0.0
  injectable_generator: ^3.1.0
  flutter_bloc: ^9.1.1
  sqflite: ^2.4.3
  path_provider: ^2.1.6
  path: ^1.9.1
  equatable: ^2.0.8
  fpdart: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^6.0.0
  build_runner: ^2.15.0


flutter:
  assets:
    - assets/sql/
  uses-material-design: true


 
